version: '3'

services:
  # This defines a service for the Django app
  web:
    build:
      context: ./web
    container_name: web
    volumes:
      - ./web:/web

    command: ./bin/run.${ENV}.sh
    ports:
      - "8000:8000"
      - "8080:8080"

    links:
      - db:db

  # Nginx
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    volumes:
      - ./web:/web
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web:web
    ports:
      - "80:80"
    
  # This defines a service for the Postgres database
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
