version: '3'

services:
  # This defines a service for the Django app
  web:
    build:
      context: ./web
    volumes:
      - ./web:/web
      # - ./static:/static

    command: ./bin/run.${RUNNER_MODE}.sh
    ports:
      - "8000:8000"
      - "8080:8080"

    links:
      - db:db

  # Nginx
  nginx:
    build: 
      context: ./nginx
    volumes:
      - ./web:/web
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./static:/static
    links:
      - web:web
    ports:
      - "80:80"
    
  # This defines a service for the Postgres database
  db:
    image: postgres
    ports:
      - "5432:5432"
