# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Huy Chau <huy.chau@asnet.com.vn>

# Copy custom configuration file from the current directory
ADD nginx.conf /etc/nginx/conf.d/default.conf
